# Generated by Django 5.0.2 on 2024-02-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='UserName')),
                ('email', models.EmailField(max_length=254, verbose_name='UserEmail')),
                ('contact', models.IntegerField()),
                ('image', models.FileField(max_length=255, upload_to='images/')),
                ('resume', models.FileField(max_length=254, upload_to='files/')),
            ],
        ),
    ]
