# Generated by Django 5.0.2 on 2024-02-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
