# Generated by Django 5.0.2 on 2024-02-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_registrationmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='image',
            field=models.ImageField(max_length=254, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='resume',
            field=models.FileField(max_length=254, upload_to='media/files/'),
        ),
    ]
