# Generated by Django 5.0.2 on 2024-02-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_registrationmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='resume',
            field=models.FileField(max_length=254, upload_to='files/'),
        ),
    ]
